name: Test

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: Jest Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup Jest 
        run: |
          npm install --save-dev @babel/preset-env@7.x @shelf/jest-mongodb@4.x jest@29.x supertest@6.x
          [ -f .babel.config.js ] || wget https://raw.githubusercontent.com/t-bello7/Afrisplash-Backend/main/babel.config.js
          [ -f .jest.config.js ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/react-redux/.babelrc
      - name: Unit Test Report
        run: npm run test